version: "3"

services:
  client:
    build:
      context: ./client/
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
    links:
      - api
    networks:
      - webappnetwork
  api:
    build:
      context: ./api/
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./api:/api
      - /api/node_modules
      - ./LingoLab-f1e5e492d164.json:/api/LingoLab-f1e5e492d164.json
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - SENDGRID_KEY=${SENDGRID_KEY}
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongodb
    networks:
      - webappnetwork
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./data-node:/data/db
    ports:
      - 27017:27017
    command: mongod --noauth
    networks:
      - webappnetwork
networks:
  webappnetwork:
    driver: bridge
